---

- hosts: all
  become: true

  tasks:
  - name: stop current running container
    command: docker stop simple-devops-container
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm simple-devops-container
    ignore_errors: yes

  - name: remove docker image
    command: dockr rmi simple-devops-image
    ignore_errors: yes
        
  - name: pull docker image from the docker hub
    command: docker pull saijadam/simple-devops-image:latest

  - name: create a container using simple-devops-image
    command: docker run -d --name simple-devops-container -p 8080:8080 saijadam/simple-devops-image:latest
